### PR TITLE
Update out-consolegridview to Terminal.Gui 89.4

### PR DESCRIPTION
**Pull request by tig**
This PR updates `ocgv` to use the very latest `Terminal.gui` nuget package, 89.4.

0.89.4 is the release candidate for 0.90. 

Note that the `ocgv` documentation in `docs/Microsoft.PowerShell.ConsoleGuiTools/Out-ConsoleGridView.md` is way out of date still.

### CODE REVIEW

**Review by TylerLeonhardt — APPROVED** [review]
LGTM

**Comment by TylerLeonhardt** [comment]
With this version, I think we can ship 🙂

**Comment by TylerLeonhardt** [comment]
BTW, the cmdlet being out of date.... You just need to run PlatyPS. There's an Invoke Build task here that will generate it:

https://github.com/PowerShell/GraphicalTools/blob/master/GraphicalTools.build.ps1#L170

**Comment by tig** [comment]
> BTW, the cmdlet being out of date.... You just need to run PlatyPS. There's an Invoke Build task here that will generate it:
> 
> https://github.com/PowerShell/GraphicalTools/blob/master/GraphicalTools.build.ps1#L170

Doing `./Build.ps1 BuildCmdletHelp` did not update the `docs/Out-ConsoleGridView.md` as I expected from your comment. Did I misunderstand? Is there another step?

**Comment by TylerLeonhardt** [comment]
First, import your newly built module, then run:

```pwsh
Invoke-Build BuildCmdletHelp -ModuleName "Microsoft.PowerShell.ConsoleGuiTools
```

**Comment by TylerLeonhardt** [comment]
Actually... That might only build the MAML... In any case, if you don't wanna fix the markdown, I can do it before we ship

**Comment by TylerLeonhardt** [comment]
@tig all good to merge?

**Comment by tig** [comment]
> @tig all good to merge?

Yessir.

**Pull request merged**
