### PR TITLE
Join-Path takes only two parameters

### PR DESCRIPTION
**Pull request by dfinke**
Don't know if this is the `$destDir` wanted. It now builds on my box.

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
Join-Path in PowerShell 6+ takes any number of parameters now 😉

**Comment by dfinke** [comment]
Yeah, wanted to build it from 5.1. Guess ps core is recommended.

**Comment by TylerLeonhardt** [comment]
It is - but if you change this PR to use:

`[System.IO.Path]::Combine`

I would accept it.

**Comment by corbob** [comment]
According to [the psd1](https://github.com/PowerShell/GraphicalTools/blob/master/src/Microsoft.PowerShell.GraphicalTools/Microsoft.PowerShell.GraphicalTools.psd1#L33) Core is required... it won't even import on 5.1...

**Comment by TylerLeonhardt** [comment]
Good point. I'll close this now since it's not been updated too.

**Pull request closed without merging**
