### PR TITLE
Upgrade to Terminal.Gui 1.0

### LINKED ISSUE #140: OCGV: Upgrade to use Terminal.Gui v1.0
Terminal.Gui is about to declare v1.0.

Release 1.0.0-beta.8 is currently available as a nugget pre-release and is a near final release candidate.

### PR DESCRIPTION
**Pull request by tig**
Fixes #140 

This PR uses Terminal.Gui v1.0.0-beta.8 which is a near-final RC of 1.0.

@TylerLeonhardt and others: Please pull this PR down and test! 

I will update it to use Terminal.Gui 1.0 once it's in the bag.

### CODE REVIEW

**Comment by tig** [comment]
I have updated this PR with the very latest (1.0.0-beta.11).

One more big bug to squash before 1.0 is in the can: https://github.com/migueldeicaza/gui.cs/discussions/1060

**Comment by andschwa** [comment]
@tig is there any particular testing I should do for this?

**Comment by tig** [comment]
> @tig is there any particular testing I should do for this?

Yes, please!

- Play with the various `-OutputMode` options with various inputs to ensure the right objects are returned. 
- Test on non-Windows platforms, esp Mac iTerm. Ensure glyps appear correctly.
- On non-Windows platform ensure that the terminal is reset properly after `ocgv` returns

Thanks!!

**Comment by tig** [comment]
Woot!

Terminal.Gui 1.0 is OUT.

It would be awesome if the PowerShell team could now do a release of `GraphicalTools` so that `OutConsoleGridView` could be used with the latest & greatest. Who can I buy beers for to make that happen? ;-)  

@SteveL-MSFT? @TylerLeonhardt (even though you moved on)? @andschwa?

Hugs all around.

**Comment by andschwa** [comment]
@tig It's actually on my list to do...this week! There was another fix that landed which we wanted to release for as well, and it was "end of April" that I was going to do it by, so excellent timing! I'll test both out and do just one release 😄

**Comment by andschwa** [comment]
> > @tig is there any particular testing I should do for this?
> 
> Yes, please!
> 
> * Play with the various `-OutputMode` options with various inputs to ensure the right objects are returned.
> * Test on non-Windows platforms, esp Mac iTerm. Ensure glyps appear correctly.
> * On non-Windows platform ensure that the terminal is reset properly after `ocgv` returns
> 
> Thanks!!

All three of these things working great on my macMini (with an M1). I had to modify what SDK it was built against to get it to build, but that was just temporary.

**Review by andschwa — APPROVED** [review]
Works great, thanks!

**Pull request merged**
