### PR TITLE
Updates to PS 7.2, net60, and Terminal.Gui 1.6

### LINKED ISSUE #151: OCGV: Filter edit chops off first char of filter string passed on command line
n3eQi8I 1

Or, do

```powerhsell
Get-Process | Out-ConsoleGridView -Filter test
```

This doesn't appear to impact filter functionality, it's just that the first character is not visible. If one backspace to delete all of the filter string, it DOES delete that first char.

### PR DESCRIPTION
**Pull request by tig**
This PR updates the project to Powershell 7.2, net60, and Terminal.Gui 1.6.

This is in prep for some bug fixes to `Out-ConsoleGridView`.

* In testing Terminal.Gui 1.6, I found a regression: `-Filter` usage caused a crash. I tracked this down to how OCGV was using the `Label` control and found the bug in Terminal.Gui: If `Label` is constructed with `string.Empty` it barfs (See https://github.com/migueldeicaza/gui.cs/issues/1769). The workaround is to construct it with `" "`. In addition, since Terminal.Gui 1.0, the ability to show/hide controls was added enabling a simplification of the logic for when the filter text changes. 

* Fixes #151 (serendipitously)

* Diables building of the Avalona based `Out-GridView`...  because it is dependent on versions of ReactivUI that are not supported by net60 and in diving in to try to fix I found a rabbit hole. Since no work will be done on the Avalona PS GUI components I think it's ok to not build them anymore.

### CODE REVIEW

**Comment by andschwa** [comment]
> * Diables building of the Avalona based `Out-GridView`...  because it is dependent on versions of ReactivUI that are not supported by net60 and in diving in to try to fix I found a rabbit hole. Since no work will be done on the Avalona PS GUI components I think it's ok to not build them anymore.

Went down a similar rabbit hole yesterday. It seems...doable...but yeah a bit of a headache because of the change to lifetime management in the updates to Avalonia.

> Since no work will be done on the Avalona PS GUI components I think it's ok to not build them anymore.

What do you mean by this exactly? It looked to me like the Out-GridView package was entirely dependent on it, but I really don't know this project at all.

**Comment by andschwa** [comment]
> * Diables building of the Avalona based `Out-GridView`...  because it is dependent on versions of ReactivUI that are not supported by net60 and in diving in to try to fix I found a rabbit hole. Since no work will be done on the Avalona PS GUI components I think it's ok to not build them anymore.

Went down a similar rabbit hole yesterday. It seems...doable...but yeah a bit of a headache because of the change to lifetime management in the updates to Avalonia.

> Since no work will be done on the Avalona PS GUI components I think it's ok to not build them anymore.

What do you mean by this exactly? It looked to me like the Out-GridView package was entirely dependent on it, but I really don't know this project at all.

**Comment by tig** [comment]
> What do you mean by this exactly? It looked to me like the Out-GridView package was entirely dependent on it, but I really don't know this project at all.

`out-gridview` *is* the Avalonia-based package.

**Comment by andschwa** [comment]
Heh, vs `Out-ConsoleGridView` emphasis on *Console* lol.

**Comment by andschwa** [comment]
Ah, dang, can you make one more update? v1.7.1 just released: https://github.com/gui-cs/Terminal.Gui/releases/tag/v1.7.1

**Comment by tig** [comment]
I'm working on an update to this PR that updates to the latest Terminal.Gui.

@SteveL-MSFT already merged several fixes that I had in this PR separately, so this PR will change to just get the latest Terminal.Gui.

Separately, I would like to upgrade OCGV to use Terminal.Gui's `TableView` which did not exist when @TylerLeonhardt first wrote OCGV. 

@SteveL-MSFT , what is your thinking on actually releasing a new GraphicalTools package? It would be awesome if you are willing to work on making that happen!

**Comment by andschwa** [comment]
@tig We are planning on releasing a new package! I just need to get to it, it's on my list for Monday. It was on my list for last Monday's community day, but I had to take the day off.

**Comment by tig** [comment]
> @tig We are planning on releasing a new package! I just need to get to it, it's on my list for Monday. It was on my list for last Monday's community day, but I had to take the day off.

Well damn, then I better get to work on the re-write! LOL.

Seriously, if you just release with the Terminal.Gui v1.7.1 update and the fix for #151 (which I'm not sure is actually fixed; will do so today) that'd be mucho awesome.

**Comment by andschwa** [comment]
The unfortunate bit is that I think a lot of work needs to go into setting up more secure and compliant release pipelines. I.e. we cannot build it locally and upload that package as a release, we have to automate it. The good news is that I've done that for other projects in the past so I'm not wholly unfamiliar, the bad news is that it's still quite an arduous process.

**Comment by tig** [comment]
> The unfortunate bit is that I think a lot of work needs to go into setting up more secure and compliant release pipelines. I.e. we cannot build it locally and upload that package as a release, we have to automate it. The good news is that I've done that for other projects in the past so I'm not wholly unfamiliar, the bad news is that it's still quite an arduous process.

I get it. I'll do everything I can to make it easy for you. Other than ensuring the PRs are good, how else can I help?

**Comment by tig** [comment]
Superseded by #161; closing.

**Pull request closed without merging**
